//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 5/05/2017 4:05:36 PM
namespace EIV.Demo.Model
{
    /// <summary>
    /// There are no comments for CitySingle in the schema.
    /// </summary>
    public partial class CitySingle : global::Microsoft.OData.Client.DataServiceQuerySingle<City>
    {
        /// <summary>
        /// Initialize a new CitySingle object.
        /// </summary>
        public CitySingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CitySingle object.
        /// </summary>
        public CitySingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CitySingle object.
        /// </summary>
        public CitySingle(global::Microsoft.OData.Client.DataServiceQuerySingle<City> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for State in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::EIV.Demo.Model.StateSingle State
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._State == null))
                {
                    this._State = new global::EIV.Demo.Model.StateSingle(this.Context, GetPath("State"));
                }
                return this._State;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::EIV.Demo.Model.StateSingle _State;
    }
    /// <summary>
    /// There are no comments for City in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class City : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new City object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="state">Initial value of State.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static City CreateCity(int ID, global::EIV.Demo.Model.State state)
        {
            City city = new City();
            city.Id = ID;
            if ((state == null))
            {
                throw new global::System.ArgumentNullException("state");
            }
            city.State = state;
            return city;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property PostalCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string PostalCode
        {
            get
            {
                return this._PostalCode;
            }
            set
            {
                this.OnPostalCodeChanging(value);
                this._PostalCode = value;
                this.OnPostalCodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _PostalCode;
        partial void OnPostalCodeChanging(string value);
        partial void OnPostalCodeChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property State in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::EIV.Demo.Model.State State
        {
            get
            {
                return this._State;
            }
            set
            {
                this.OnStateChanging(value);
                this._State = value;
                this.OnStateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::EIV.Demo.Model.State _State;
        partial void OnStateChanging(global::EIV.Demo.Model.State value);
        partial void OnStateChanged();
    }
    /// <summary>
    /// There are no comments for StateSingle in the schema.
    /// </summary>
    public partial class StateSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<State>
    {
        /// <summary>
        /// Initialize a new StateSingle object.
        /// </summary>
        public StateSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new StateSingle object.
        /// </summary>
        public StateSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new StateSingle object.
        /// </summary>
        public StateSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<State> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Country in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::EIV.Demo.Model.CountrySingle Country
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Country == null))
                {
                    this._Country = new global::EIV.Demo.Model.CountrySingle(this.Context, GetPath("Country"));
                }
                return this._Country;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::EIV.Demo.Model.CountrySingle _Country;
        /// <summary>
        /// There are no comments for Cities in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.City> Cities
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Cities == null))
                {
                    this._Cities = Context.CreateQuery<global::EIV.Demo.Model.City>(GetPath("Cities"));
                }
                return this._Cities;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.City> _Cities;
    }
    /// <summary>
    /// There are no comments for State in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class State : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new State object.
        /// </summary>
        /// <param name="countryId">Initial value of CountryId.</param>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="country">Initial value of Country.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static State CreateState(int countryId, int ID, global::EIV.Demo.Model.Country country)
        {
            State state = new State();
            state.CountryId = countryId;
            state.Id = ID;
            if ((country == null))
            {
                throw new global::System.ArgumentNullException("country");
            }
            state.Country = country;
            return state;
        }
        /// <summary>
        /// There are no comments for Property CountryId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int CountryId
        {
            get
            {
                return this._CountryId;
            }
            set
            {
                this.OnCountryIdChanging(value);
                this._CountryId = value;
                this.OnCountryIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _CountryId;
        partial void OnCountryIdChanging(int value);
        partial void OnCountryIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Country in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::EIV.Demo.Model.Country Country
        {
            get
            {
                return this._Country;
            }
            set
            {
                this.OnCountryChanging(value);
                this._Country = value;
                this.OnCountryChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::EIV.Demo.Model.Country _Country;
        partial void OnCountryChanging(global::EIV.Demo.Model.Country value);
        partial void OnCountryChanged();
        /// <summary>
        /// There are no comments for Property Cities in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Collections.ObjectModel.Collection<global::EIV.Demo.Model.City> Cities
        {
            get
            {
                return this._Cities;
            }
            set
            {
                this.OnCitiesChanging(value);
                this._Cities = value;
                this.OnCitiesChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Collections.ObjectModel.Collection<global::EIV.Demo.Model.City> _Cities = new global::System.Collections.ObjectModel.Collection<global::EIV.Demo.Model.City>();
        partial void OnCitiesChanging(global::System.Collections.ObjectModel.Collection<global::EIV.Demo.Model.City> value);
        partial void OnCitiesChanged();
    }
    /// <summary>
    /// There are no comments for CountrySingle in the schema.
    /// </summary>
    public partial class CountrySingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Country>
    {
        /// <summary>
        /// Initialize a new CountrySingle object.
        /// </summary>
        public CountrySingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CountrySingle object.
        /// </summary>
        public CountrySingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CountrySingle object.
        /// </summary>
        public CountrySingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Country> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for States in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.State> States
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._States == null))
                {
                    this._States = Context.CreateQuery<global::EIV.Demo.Model.State>(GetPath("States"));
                }
                return this._States;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.State> _States;
    }
    /// <summary>
    /// There are no comments for Country in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Country : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Country object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Country CreateCountry(int ID)
        {
            Country country = new Country();
            country.Id = ID;
            return country;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property DDI in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string DDI
        {
            get
            {
                return this._DDI;
            }
            set
            {
                this.OnDDIChanging(value);
                this._DDI = value;
                this.OnDDIChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _DDI;
        partial void OnDDIChanging(string value);
        partial void OnDDIChanged();
        /// <summary>
        /// There are no comments for Property States in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Collections.ObjectModel.Collection<global::EIV.Demo.Model.State> States
        {
            get
            {
                return this._States;
            }
            set
            {
                this.OnStatesChanging(value);
                this._States = value;
                this.OnStatesChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Collections.ObjectModel.Collection<global::EIV.Demo.Model.State> _States = new global::System.Collections.ObjectModel.Collection<global::EIV.Demo.Model.State>();
        partial void OnStatesChanging(global::System.Collections.ObjectModel.Collection<global::EIV.Demo.Model.State> value);
        partial void OnStatesChanged();
    }
    /// <summary>
    /// There are no comments for ClientSingle in the schema.
    /// </summary>
    public partial class ClientSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Client>
    {
        /// <summary>
        /// Initialize a new ClientSingle object.
        /// </summary>
        public ClientSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ClientSingle object.
        /// </summary>
        public ClientSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ClientSingle object.
        /// </summary>
        public ClientSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Client> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Client in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Client : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Client object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="dOB">Initial value of DOB.</param>
        /// <param name="clientType">Initial value of ClientType.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Client CreateClient(int ID, global::System.DateTimeOffset dOB, global::EIV.Demo.Model.EnumClientType clientType)
        {
            Client client = new Client();
            client.Id = ID;
            client.DOB = dOB;
            client.ClientType = clientType;
            return client;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property DOB in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.DateTimeOffset DOB
        {
            get
            {
                return this._DOB;
            }
            set
            {
                this.OnDOBChanging(value);
                this._DOB = value;
                this.OnDOBChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _DOB;
        partial void OnDOBChanging(global::System.DateTimeOffset value);
        partial void OnDOBChanged();
        /// <summary>
        /// There are no comments for Property ClientType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::EIV.Demo.Model.EnumClientType ClientType
        {
            get
            {
                return this._ClientType;
            }
            set
            {
                this.OnClientTypeChanging(value);
                this._ClientType = value;
                this.OnClientTypeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::EIV.Demo.Model.EnumClientType _ClientType;
        partial void OnClientTypeChanging(global::EIV.Demo.Model.EnumClientType value);
        partial void OnClientTypeChanged();
    }
    /// <summary>
    /// There are no comments for UserSingle in the schema.
    /// </summary>
    public partial class UserSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<User>
    {
        /// <summary>
        /// Initialize a new UserSingle object.
        /// </summary>
        public UserSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new UserSingle object.
        /// </summary>
        public UserSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new UserSingle object.
        /// </summary>
        public UserSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<User> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for MenuItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.MenuItem> MenuItems
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._MenuItems == null))
                {
                    this._MenuItems = Context.CreateQuery<global::EIV.Demo.Model.MenuItem>(GetPath("MenuItems"));
                }
                return this._MenuItems;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.MenuItem> _MenuItems;
    }
    /// <summary>
    /// There are no comments for User in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class User : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="fechaAlta">Initial value of FechaAlta.</param>
        /// <param name="fechaBaja">Initial value of FechaBaja.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static User CreateUser(string name, global::System.DateTimeOffset fechaAlta, global::System.DateTimeOffset fechaBaja, int ID)
        {
            User user = new User();
            user.Name = name;
            user.FechaAlta = fechaAlta;
            user.FechaBaja = fechaBaja;
            user.Id = ID;
            return user;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property FechaAlta in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.DateTimeOffset FechaAlta
        {
            get
            {
                return this._FechaAlta;
            }
            set
            {
                this.OnFechaAltaChanging(value);
                this._FechaAlta = value;
                this.OnFechaAltaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _FechaAlta;
        partial void OnFechaAltaChanging(global::System.DateTimeOffset value);
        partial void OnFechaAltaChanged();
        /// <summary>
        /// There are no comments for Property FechaBaja in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.DateTimeOffset FechaBaja
        {
            get
            {
                return this._FechaBaja;
            }
            set
            {
                this.OnFechaBajaChanging(value);
                this._FechaBaja = value;
                this.OnFechaBajaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _FechaBaja;
        partial void OnFechaBajaChanging(global::System.DateTimeOffset value);
        partial void OnFechaBajaChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property MenuItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Collections.ObjectModel.Collection<global::EIV.Demo.Model.MenuItem> MenuItems
        {
            get
            {
                return this._MenuItems;
            }
            set
            {
                this.OnMenuItemsChanging(value);
                this._MenuItems = value;
                this.OnMenuItemsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Collections.ObjectModel.Collection<global::EIV.Demo.Model.MenuItem> _MenuItems = new global::System.Collections.ObjectModel.Collection<global::EIV.Demo.Model.MenuItem>();
        partial void OnMenuItemsChanging(global::System.Collections.ObjectModel.Collection<global::EIV.Demo.Model.MenuItem> value);
        partial void OnMenuItemsChanged();
    }
    /// <summary>
    /// There are no comments for MenuItemSingle in the schema.
    /// </summary>
    public partial class MenuItemSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<MenuItem>
    {
        /// <summary>
        /// Initialize a new MenuItemSingle object.
        /// </summary>
        public MenuItemSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new MenuItemSingle object.
        /// </summary>
        public MenuItemSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new MenuItemSingle object.
        /// </summary>
        public MenuItemSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<MenuItem> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for ParentMenu in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::EIV.Demo.Model.MenuItemSingle ParentMenu
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ParentMenu == null))
                {
                    this._ParentMenu = new global::EIV.Demo.Model.MenuItemSingle(this.Context, GetPath("ParentMenu"));
                }
                return this._ParentMenu;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::EIV.Demo.Model.MenuItemSingle _ParentMenu;
        /// <summary>
        /// There are no comments for SubItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.MenuItem> SubItems
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._SubItems == null))
                {
                    this._SubItems = Context.CreateQuery<global::EIV.Demo.Model.MenuItem>(GetPath("SubItems"));
                }
                return this._SubItems;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.MenuItem> _SubItems;
    }
    /// <summary>
    /// There are no comments for MenuItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class MenuItem : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new MenuItem object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="text">Initial value of Text.</param>
        /// <param name="isEnabled">Initial value of IsEnabled.</param>
        /// <param name="isHidden">Initial value of IsHidden.</param>
        /// <param name="isSeparator">Initial value of IsSeparator.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static MenuItem CreateMenuItem(string name, 
                    string text, 
                    bool isEnabled, 
                    bool isHidden, 
                    bool isSeparator, 
                    int ID)
        {
            MenuItem menuItem = new MenuItem();
            menuItem.Name = name;
            menuItem.Text = text;
            menuItem.IsEnabled = isEnabled;
            menuItem.IsHidden = isHidden;
            menuItem.IsSeparator = isSeparator;
            menuItem.Id = ID;
            return menuItem;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Text in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Text
        {
            get
            {
                return this._Text;
            }
            set
            {
                this.OnTextChanging(value);
                this._Text = value;
                this.OnTextChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Text;
        partial void OnTextChanging(string value);
        partial void OnTextChanged();
        /// <summary>
        /// There are no comments for Property IconUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string IconUrl
        {
            get
            {
                return this._IconUrl;
            }
            set
            {
                this.OnIconUrlChanging(value);
                this._IconUrl = value;
                this.OnIconUrlChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _IconUrl;
        partial void OnIconUrlChanging(string value);
        partial void OnIconUrlChanged();
        /// <summary>
        /// There are no comments for Property IsEnabled in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public bool IsEnabled
        {
            get
            {
                return this._IsEnabled;
            }
            set
            {
                this.OnIsEnabledChanging(value);
                this._IsEnabled = value;
                this.OnIsEnabledChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private bool _IsEnabled;
        partial void OnIsEnabledChanging(bool value);
        partial void OnIsEnabledChanged();
        /// <summary>
        /// There are no comments for Property IsHidden in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public bool IsHidden
        {
            get
            {
                return this._IsHidden;
            }
            set
            {
                this.OnIsHiddenChanging(value);
                this._IsHidden = value;
                this.OnIsHiddenChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private bool _IsHidden;
        partial void OnIsHiddenChanging(bool value);
        partial void OnIsHiddenChanged();
        /// <summary>
        /// There are no comments for Property IsSeparator in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public bool IsSeparator
        {
            get
            {
                return this._IsSeparator;
            }
            set
            {
                this.OnIsSeparatorChanging(value);
                this._IsSeparator = value;
                this.OnIsSeparatorChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private bool _IsSeparator;
        partial void OnIsSeparatorChanging(bool value);
        partial void OnIsSeparatorChanged();
        /// <summary>
        /// There are no comments for Property ToolTip in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string ToolTip
        {
            get
            {
                return this._ToolTip;
            }
            set
            {
                this.OnToolTipChanging(value);
                this._ToolTip = value;
                this.OnToolTipChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _ToolTip;
        partial void OnToolTipChanging(string value);
        partial void OnToolTipChanged();
        /// <summary>
        /// There are no comments for Property ClassName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string ClassName
        {
            get
            {
                return this._ClassName;
            }
            set
            {
                this.OnClassNameChanging(value);
                this._ClassName = value;
                this.OnClassNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _ClassName;
        partial void OnClassNameChanging(string value);
        partial void OnClassNameChanged();
        /// <summary>
        /// There are no comments for Property ClassMethod in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string ClassMethod
        {
            get
            {
                return this._ClassMethod;
            }
            set
            {
                this.OnClassMethodChanging(value);
                this._ClassMethod = value;
                this.OnClassMethodChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _ClassMethod;
        partial void OnClassMethodChanging(string value);
        partial void OnClassMethodChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property ParentMenu in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::EIV.Demo.Model.MenuItem ParentMenu
        {
            get
            {
                return this._ParentMenu;
            }
            set
            {
                this.OnParentMenuChanging(value);
                this._ParentMenu = value;
                this.OnParentMenuChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::EIV.Demo.Model.MenuItem _ParentMenu;
        partial void OnParentMenuChanging(global::EIV.Demo.Model.MenuItem value);
        partial void OnParentMenuChanged();
        /// <summary>
        /// There are no comments for Property SubItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Collections.ObjectModel.Collection<global::EIV.Demo.Model.MenuItem> SubItems
        {
            get
            {
                return this._SubItems;
            }
            set
            {
                this.OnSubItemsChanging(value);
                this._SubItems = value;
                this.OnSubItemsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Collections.ObjectModel.Collection<global::EIV.Demo.Model.MenuItem> _SubItems = new global::System.Collections.ObjectModel.Collection<global::EIV.Demo.Model.MenuItem>();
        partial void OnSubItemsChanging(global::System.Collections.ObjectModel.Collection<global::EIV.Demo.Model.MenuItem> value);
        partial void OnSubItemsChanged();
    }
    /// <summary>
    /// There are no comments for EnumClientType in the schema.
    /// </summary>
    public enum EnumClientType
    {
        Basic = 0,
        Premier = 1,
        Unknown = -1
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::EIV.Demo.Model.City as global::EIV.Demo.Model.CitySingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::EIV.Demo.Model.CitySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.City> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::EIV.Demo.Model.CitySingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::EIV.Demo.Model.City as global::EIV.Demo.Model.CitySingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::EIV.Demo.Model.CitySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.City> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::EIV.Demo.Model.CitySingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::EIV.Demo.Model.State as global::EIV.Demo.Model.StateSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::EIV.Demo.Model.StateSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.State> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::EIV.Demo.Model.StateSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::EIV.Demo.Model.State as global::EIV.Demo.Model.StateSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::EIV.Demo.Model.StateSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.State> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::EIV.Demo.Model.StateSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::EIV.Demo.Model.Country as global::EIV.Demo.Model.CountrySingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::EIV.Demo.Model.CountrySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.Country> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::EIV.Demo.Model.CountrySingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::EIV.Demo.Model.Country as global::EIV.Demo.Model.CountrySingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::EIV.Demo.Model.CountrySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.Country> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::EIV.Demo.Model.CountrySingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::EIV.Demo.Model.Client as global::EIV.Demo.Model.ClientSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::EIV.Demo.Model.ClientSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.Client> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::EIV.Demo.Model.ClientSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::EIV.Demo.Model.Client as global::EIV.Demo.Model.ClientSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::EIV.Demo.Model.ClientSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.Client> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::EIV.Demo.Model.ClientSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::EIV.Demo.Model.User as global::EIV.Demo.Model.UserSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::EIV.Demo.Model.UserSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.User> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::EIV.Demo.Model.UserSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::EIV.Demo.Model.User as global::EIV.Demo.Model.UserSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::EIV.Demo.Model.UserSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.User> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::EIV.Demo.Model.UserSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::EIV.Demo.Model.MenuItem as global::EIV.Demo.Model.MenuItemSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::EIV.Demo.Model.MenuItemSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.MenuItem> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::EIV.Demo.Model.MenuItemSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::EIV.Demo.Model.MenuItem as global::EIV.Demo.Model.MenuItemSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::EIV.Demo.Model.MenuItemSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.MenuItem> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::EIV.Demo.Model.MenuItemSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace EIV.Demo.WebService
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Cities in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.City> Cities
        {
            get
            {
                if ((this._Cities == null))
                {
                    this._Cities = base.CreateQuery<global::EIV.Demo.Model.City>("Cities");
                }
                return this._Cities;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.City> _Cities;
        /// <summary>
        /// There are no comments for States in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.State> States
        {
            get
            {
                if ((this._States == null))
                {
                    this._States = base.CreateQuery<global::EIV.Demo.Model.State>("States");
                }
                return this._States;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.State> _States;
        /// <summary>
        /// There are no comments for Countries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.Country> Countries
        {
            get
            {
                if ((this._Countries == null))
                {
                    this._Countries = base.CreateQuery<global::EIV.Demo.Model.Country>("Countries");
                }
                return this._Countries;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.Country> _Countries;
        /// <summary>
        /// There are no comments for People in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.Client> People
        {
            get
            {
                if ((this._People == null))
                {
                    this._People = base.CreateQuery<global::EIV.Demo.Model.Client>("People");
                }
                return this._People;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.Client> _People;
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.User> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<global::EIV.Demo.Model.User>("Users");
                }
                return this._Users;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.User> _Users;
        /// <summary>
        /// There are no comments for Cities in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToCities(global::EIV.Demo.Model.City city)
        {
            base.AddObject("Cities", city);
        }
        /// <summary>
        /// There are no comments for States in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToStates(global::EIV.Demo.Model.State state)
        {
            base.AddObject("States", state);
        }
        /// <summary>
        /// There are no comments for Countries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToCountries(global::EIV.Demo.Model.Country country)
        {
            base.AddObject("Countries", country);
        }
        /// <summary>
        /// There are no comments for People in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToPeople(global::EIV.Demo.Model.Client client)
        {
            base.AddObject("People", client);
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToUsers(global::EIV.Demo.Model.User user)
        {
            base.AddObject("Users", user);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""EIV.Demo.Model"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""City"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""PostalCode"" Type=""Edm.String"" />
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <NavigationProperty Name=""State"" Type=""EIV.Demo.Model.State"" Nullable=""false"" />
      </EntityType>
      <EntityType Name=""State"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""CountryId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <NavigationProperty Name=""Country"" Type=""EIV.Demo.Model.Country"" Nullable=""false"">
          <ReferentialConstraint Property=""CountryId"" ReferencedProperty=""Id"" />
        </NavigationProperty>
        <NavigationProperty Name=""Cities"" Type=""Collection(EIV.Demo.Model.City)"" />
      </EntityType>
      <EntityType Name=""Country"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""DDI"" Type=""Edm.String"" />
        <NavigationProperty Name=""States"" Type=""Collection(EIV.Demo.Model.State)"" />
      </EntityType>
      <EntityType Name=""Client"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""FirstName"" Type=""Edm.String"" />
        <Property Name=""LastName"" Type=""Edm.String"" />
        <Property Name=""DOB"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""ClientType"" Type=""EIV.Demo.Model.EnumClientType"" Nullable=""false"" />
      </EntityType>
      <EntityType Name=""User"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Name"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""FechaAlta"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""FechaBaja"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <NavigationProperty Name=""MenuItems"" Type=""Collection(EIV.Demo.Model.MenuItem)"" />
      </EntityType>
      <EntityType Name=""MenuItem"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Name"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""Text"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""IconUrl"" Type=""Edm.String"" />
        <Property Name=""IsEnabled"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""IsHidden"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""IsSeparator"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""ToolTip"" Type=""Edm.String"" />
        <Property Name=""ClassName"" Type=""Edm.String"" />
        <Property Name=""ClassMethod"" Type=""Edm.String"" />
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <NavigationProperty Name=""ParentMenu"" Type=""EIV.Demo.Model.MenuItem"" />
        <NavigationProperty Name=""SubItems"" Type=""Collection(EIV.Demo.Model.MenuItem)"" />
      </EntityType>
      <EnumType Name=""EnumClientType"">
        <Member Name=""Basic"" Value=""0"" />
        <Member Name=""Premier"" Value=""1"" />
        <Member Name=""Unknown"" Value=""-1"" />
      </EnumType>
    </Schema>
    <Schema Namespace=""EIV.Demo.WebService"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <Action Name=""PaisAction"" IsBound=""true"">
        <Parameter Name=""bindingParameter"" Type=""EIV.Demo.Model.Country"" />
        <Parameter Name=""sectorId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Parameter Name=""fechaIngreso"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Parameter Name=""StateIDs"" Type=""Collection(EIV.Demo.Model.State)"" />
        <ReturnType Type=""EIV.Demo.Model.Client"" />
      </Action>
      <Action Name=""StateListAction"" IsBound=""true"">
        <Parameter Name=""bindingParameter"" Type=""EIV.Demo.Model.Country"" />
        <Parameter Name=""StateIDs"" Type=""Collection(EIV.Demo.Model.State)"" />
        <ReturnType Type=""Edm.Int32"" Nullable=""false"" />
      </Action>
      <Action Name=""Transfer"" IsBound=""true"">
        <Parameter Name=""bindingParameter"" Type=""EIV.Demo.Model.Client"" />
        <ReturnType Type=""Collection(EIV.Demo.Model.Client)"" />
      </Action>
      <Function Name=""TotalPaises"" IsBound=""true"">
        <Parameter Name=""bindingParameter"" Type=""Collection(EIV.Demo.Model.Country)"" />
        <ReturnType Type=""Edm.Int32"" Nullable=""false"" />
      </Function>
      <Action Name=""AuthenticateUser"" IsBound=""true"">
        <Parameter Name=""bindingParameter"" Type=""Collection(EIV.Demo.Model.User)"" />
        <Parameter Name=""username"" Type=""Edm.String"" Unicode=""false"" />
        <Parameter Name=""password"" Type=""Edm.String"" Unicode=""false"" />
        <ReturnType Type=""EIV.Demo.Model.User"" />
      </Action>
      <Action Name=""SetMenu"" IsBound=""true"">
        <Parameter Name=""bindingParameter"" Type=""Collection(EIV.Demo.Model.User)"" />
        <Parameter Name=""username"" Type=""Edm.String"" Unicode=""false"" />
        <Parameter Name=""menuitems"" Type=""Edm.String"" Unicode=""false"" />
        <ReturnType Type=""Edm.Boolean"" Nullable=""false"" />
      </Action>
      <EntityContainer Name=""Container"">
        <EntitySet Name=""Cities"" EntityType=""EIV.Demo.Model.City"">
          <NavigationPropertyBinding Path=""State"" Target=""States"" />
        </EntitySet>
        <EntitySet Name=""States"" EntityType=""EIV.Demo.Model.State"">
          <NavigationPropertyBinding Path=""Country"" Target=""Countries"" />
          <NavigationPropertyBinding Path=""Cities"" Target=""Cities"" />
        </EntitySet>
        <EntitySet Name=""Countries"" EntityType=""EIV.Demo.Model.Country"">
          <NavigationPropertyBinding Path=""States"" Target=""States"" />
        </EntitySet>
        <EntitySet Name=""People"" EntityType=""EIV.Demo.Model.Client"" />
        <EntitySet Name=""Users"" EntityType=""EIV.Demo.Model.User"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// There are no comments for TotalPaises in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceQuerySingle<int> TotalPaises(this global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.Country> source)
        {
            if (!source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return source.CreateFunctionQuerySingle<int>("EIV.Demo.WebService.TotalPaises", false);
        }
        /// <summary>
        /// There are no comments for PaisAction in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceActionQuerySingle<global::EIV.Demo.Model.Client> PaisAction(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::EIV.Demo.Model.Country> source, int sectorId, global::System.DateTimeOffset fechaIngreso, global::System.Collections.Generic.ICollection<global::EIV.Demo.Model.State> StateIDs)
        {
            if (!source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuerySingle<global::EIV.Demo.Model.Client>(source.Context, source.AppendRequestUri("EIV.Demo.WebService.PaisAction"), new global::Microsoft.OData.Client.BodyOperationParameter("sectorId", sectorId),
                    new global::Microsoft.OData.Client.BodyOperationParameter("fechaIngreso", fechaIngreso),
                    new global::Microsoft.OData.Client.BodyOperationParameter("StateIDs", StateIDs));
        }
        /// <summary>
        /// There are no comments for StateListAction in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceActionQuerySingle<int> StateListAction(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::EIV.Demo.Model.Country> source, global::System.Collections.Generic.ICollection<global::EIV.Demo.Model.State> StateIDs)
        {
            if (!source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuerySingle<int>(source.Context, source.AppendRequestUri("EIV.Demo.WebService.StateListAction"), new global::Microsoft.OData.Client.BodyOperationParameter("StateIDs", StateIDs));
        }
        /// <summary>
        /// There are no comments for Transfer in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceActionQuery<global::EIV.Demo.Model.Client> Transfer(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::EIV.Demo.Model.Client> source)
        {
            if (!source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuery<global::EIV.Demo.Model.Client>(source.Context, source.AppendRequestUri("EIV.Demo.WebService.Transfer"));
        }
        /// <summary>
        /// There are no comments for AuthenticateUser in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceActionQuerySingle<global::EIV.Demo.Model.User> AuthenticateUser(this global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.User> source, string username, string password)
        {
            if (!source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuerySingle<global::EIV.Demo.Model.User>(source.Context, source.AppendRequestUri("EIV.Demo.WebService.AuthenticateUser"), new global::Microsoft.OData.Client.BodyOperationParameter("username", username),
                    new global::Microsoft.OData.Client.BodyOperationParameter("password", password));
        }
        /// <summary>
        /// There are no comments for SetMenu in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceActionQuerySingle<bool> SetMenu(this global::Microsoft.OData.Client.DataServiceQuery<global::EIV.Demo.Model.User> source, string username, string menuitems)
        {
            if (!source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuerySingle<bool>(source.Context, source.AppendRequestUri("EIV.Demo.WebService.SetMenu"), new global::Microsoft.OData.Client.BodyOperationParameter("username", username),
                    new global::Microsoft.OData.Client.BodyOperationParameter("menuitems", menuitems));
        }
    }
}
